name: Build and Publish Docker Image on Release
on:
  release:
    types: [published]
jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Makefile
        run: |
           git config --global url."https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/".insteadOf "https://github.com/"
           go env -w GOPRIVATE=github.com/<repo_url>/*
           export GIT_TOKEN=${{ secrets.GIT_TOKEN }}
           export GOPRIVATE=github.com/treeleaftech
           make build 
      
      - name: Zip the release bundle
        run: |
          cp -r bin/<go_app_name> .
          zip <go_app_name>.zip <go_app_name> config.yaml
  
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: <go_app_name>.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
